### ISSUE TITLE
Handle image paths with a space

### ISSUE THREAD

**Issue by chrahunt** [csbun/atom-markclip#1]
I use [markdown-preview-plus](https://github.com/Galadirith/markdown-preview-plus) which uses [markdown-it](https://github.com/markdown-it/markdown-it) to render markdown. markdown-it conforms to commonmark and requires paths with special characters to be escaped or the whole path surrounded in angle brackets, as seen [here](http://spec.commonmark.org/0.18/#link-destination). When the name of the file I am pasting into with atom-markclip itself has a space then the folder created for the image has a space and it is not rendered properly. Can an option be added to surround a path in angle brackets if the path contains spaces or any other special character?

**Comment by csbun** [comment]
Is the space so necessary for the folder created for the image? If NOT, I think we can just replace it with some other characters like `-` or `_`.

**Comment by chrahunt** [comment]
That would be fine for me. There's the obvious edge case where you have another file with a similar name but with some spaces replaced with `-` and pasting images into both may mix the two in the single image folder, but that doesn't seem like something to really worry about.

If you're choosing one or the other instead of a configurable symbol I would vote in favor of `-`. It seems to be more popular as a space-replacement.

**Comment by csbun** [comment]
Done! [v0.2.2](https://atom.io/packages/markclip)
