### ISSUE TITLE
Pasting into "Find in project" field outside of a file does not work

### ISSUE THREAD

**Issue by JamesChevalier** [csbun/atom-markclip#12]
- Open any file in your project
- Select any text in the file, and `command-c` to copy it
- `command-shift-f` to open the "Find in project" search form
- `command-v` to paste text into the search field
- From this "Project find results" window, `command-shift-f` to focus the "Find in project" search form
- When you try to `command-v` to paste text into the search field, nothing happens

**Comment by csbun** [comment]
After copying text to the clipboard, `command-v` will paste the text into the "Find in project" field. atom-markclip won't do anything in this process.

**Comment by JamesChevalier** [comment]
🤷‍♂ If I don't have the markclip plugin installed, then I can paste into the "Find in project field" from within the "Project Find Results" view. If I install the markclip plugin, that ability goes away.

If you can't reproduce this issue from the process above, then there must be some combination of plugins that's causing this for me that just happens to include markclip.

**Comment by csbun** [comment]
Yes, I install the latest Atom and with markclip plugin only, it works well.

**Comment by JamesChevalier** [comment]
This must arise out of a conflict between markclip and something else that I have installed, then. I have too many other plugins installed to determine where that resides.

Thank you for helping out!
