### ISSUE TITLE
在 mac pro 下支持图片原始尺寸保存吗？

### ISSUE THREAD

**Issue by zq99299** [csbun/atom-markclip#13]
markdown-img-paste 这个插件在 windows 下粘贴的图片正常，
但是在 mac pro 下，粘贴图片始终是截图尺寸的 2 倍

**Comment by csbun** [comment]
应该不行，从 剪贴板拿出来的图片就是 2x 图。

**Comment by zq99299** [comment]
那看来这个是 mac 系统的问题了？

**Comment by csbun** [comment]
不能这么说，本来 retina 屏幕就是 2x 像素，截图是 2x 图也是合理到。

**Comment by zq99299** [comment]
实际在用的过程中，这个表现会很头疼




------------------ 原始邮件 ------------------
发件人: "Hans Chan"<notifications@github.com>; 
发送时间: 2019年10月10日(星期四) 上午10:12
收件人: "csbun/atom-markclip"<atom-markclip@noreply.github.com>; 
抄送: "凉茶"<99299684@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [csbun/atom-markclip] 在 mac pro 下支持图片原始尺寸保存吗？ (#13)




不能这么说，本来 retina 屏幕就是 2x 像素，截图是 2x 图也是合理到。
 
&mdash;

**Comment by csbun** [comment]
会有什么问题？

**Comment by zq99299** [comment]
本来正常的只有500宽，2x的话，会占满整个屏幕，而且实际的显示效果也放大了2倍，特别特别不协调



---原始邮件---
发件人: "Hans Chan"<notifications@github.com&gt;
发送时间: 2019年10月10日(星期四) 晚上9:02
收件人: "csbun/atom-markclip"<atom-
markclip@noreply.github.com&gt;;
抄送: "mrcode"<99299684@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [csbun/atom-markclip] 在 mac pro 下支持图片原始尺寸保存吗？ (#13)



会有什么问题？

**Comment by csbun** [comment]
或许可以通过 `<img width="xxx">` 强制限制大小解决，前提是能获取到是否 retina
