### ISSUE TITLE
Change folder separator to work with Windows?

### ISSUE THREAD

**Issue by jaysnoddy** [csbun/atom-markclip#14]
I did not see it anywhere in settings, but is it possible to change the folder separators i.e  backslash or forwardslash?  Windows is stuck with a different choice from Macs/Linux/Unix. All the paths to the right folder are wrong for me.  It is trivial for me to fix each time, *if* I remember... but I am forgetful, so lots of tiny little mistakes left behind. Sorry if I missed something. Thanks!

**Comment by csbun** [comment]
We use `path.join` while [creating folders](https://github.com/csbun/atom-markclip/blob/master/lib/markclip.coffee#L71) so it should not be `/` or `\` issue.

**Comment by jaysnoddy** [comment]
Sorry I was not referring to creating new folders, that seems fine. 
I was referring to the folder separators that are part of the text placed in the open file.
The links placed in in the markdown document to images are broken, I have to change the slashes around to windows style slashes to fix.
As i said, trivial to change each time, but enough "friction" that it makes your very nice tool less nice for windows users.  
Thanks

**Comment by jaysnoddy** [comment]
in other words, I guess, an option might be nice that either places windows style slashes or Mac/linux-style slashes in the markdown document.

**Comment by SpengeSec** [comment]
I recommended markclip to my friend who uses Windows, and we had been breaking our heads over why the image's are broken.

It was the damn \ slash! 

I use Mac/Linux and have no issues whatsoever, but my friend on Windows has to replace the \ with / for the images to work... very annoying. 

Would be great if @csbun  could implement a fix for this. 

Mine:
![image](https://user-images.githubusercontent.com/60011198/88802202-0911dd80-d1ab-11ea-879c-6ba54aa4412e.png)

His:
![image](https://user-images.githubusercontent.com/60011198/88802336-36f72200-d1ab-11ea-9cff-d69ea83b7744.png)

**Comment by csbun** [comment]
I see. So we may need to add some replacement while we [insert into the editor](https://github.com/csbun/atom-markclip/blob/master/lib/markclip.coffee#L92).

**Comment by csbun** [comment]
please upgrade to v0.5.7
