### ISSUE TITLE
Add option to choose file name and/or location

### ISSUE THREAD

**Issue by jmatsushita** [csbun/atom-markclip#5]
I find that creating filename with hashes make reusing the images hard. 

It would be great if we had the following additional options in addition to Save Type:
 - `prompt for name` would ask to choose a filename after pasting. 
 - `prompt for location` would ask to choose a folder name after pasting. 

There could also be a option to set the default image save path. (either from the root folder or relative to the current file).

Cheers!

Jun

**Comment by csbun** [comment]
Try [v0.3.0](https://atom.io/packages/markclip), using setting **custom file**!

**Comment by jmatsushita** [comment]
Hey, thanks! Unfortunately `cmd-v` on osx does nothing anymore. Shall I open a new issue?

**Comment by csbun** [comment]
What's your macOS and Atom version?

I will check it out later.

**Comment by avonmoll** [comment]
I'm on Windows (Atom v1.13.0) and was also having issues with the way the keybinding was done. I created #6 to remedy this issue and it is working on my machine.

**Comment by csbun** [comment]
Great job @avonmoll ,  markclip v0.3.0 works well on Atom v1.12.x, but v1.13.
I will add keymaps `cmd-v` for macOS later.

**Comment by csbun** [comment]
Try markclip [v0.3.1](https://github.com/csbun/atom-markclip/releases/tag/v0.3.1) for Atom v1.13.x!
